const MOL = {
  ADD_INIT: 'MOL_ADD_INIT',
  ADD_DONE: 'MOL_ADD_DONE',
  ADD_FAIL: 'MOL_ADD_FAIL',
  CONVERT_DONE: 'MOL_CONVERT_DONE',
  CONVERT_FAIL: 'MOL_CONVERT_FAIL',
};

const FILE = {
  ADD_INIT: 'FILE_ADD_INIT',
  ADD_DONE: 'FILE_ADD_DONE',
  ADD_FAIL: 'FILE_ADD_FAIL',
  CONVERT_DONE: 'FILE_CONVERT_DONE',
  CONVERT_FAIL: 'FILE_CONVERT_FAIL',
  SAVE_INIT: 'FILE_SAVE_INIT',
  SAVE_DONE: 'FILE_SAVE_DONE',
};

const NOTICE = {
  MANUAL_CLEAR: 'NOTICE_MANUAL_CLEAR',
};

const PREDICT = {
  BY_PEAKS_INIT: 'PREDICT_BY_PEAKS_INIT',
  BY_PEAKS_DONE: 'PREDICT_BY_PEAKS_DONE',
  BY_PEAKS_FAIL: 'PREDICT_BY_PEAKS_FAIL',
};

const FORM = {
  UPDATE_SCAN: 'FORM_UPDATE_SCAN',
  CLEAR_SCAN: 'FORM_CLEAR_SCAN',
  SUBMIT: 'FORM_SUBMIT',
};

export {
  MOL,
  FILE,
  NOTICE,
  PREDICT,
  FORM,
};
