const FILE = {
  ADD_INIT: 'FILE_ADD_INIT',
  ADD_FAIL: 'FILE_ADD_FAIL',
  CONVERT_INIT: 'FILE_CONVERT_INIT',
  CONVERT_DONE: 'FILE_CONVERT_DONE',
  CONVERT_FAIL: 'FILE_CONVERT_FAIL',
  SAVE_INIT: 'FILE_SAVE_INIT',
  SAVE_DONE: 'FILE_SAVE_DONE',
};

const NOTICE = {
  MANUAL_CLEAR: 'NOTICE_MANUAL_CLEAR',
};

export {
  FILE,
  NOTICE,
};
