const FILE = {
  ADD_INIT: 'FILE_ADD_INIT',
  ADD_FAIL: 'FILE_ADD_FAIL',
  CONVERT_INIT: 'FILE_CONVERT_INIT',
  CONVERT_DONE: 'FILE_CONVERT_DONE',
  CONVERT_FAIL: 'FILE_CONVERT_FAIL',
  SAVE_INIT: 'FILE_SAVE_INIT',
  SAVE_DONE: 'FILE_SAVE_DONE',
};

const NOTICE = {
  MANUAL_CLEAR: 'NOTICE_MANUAL_CLEAR',
};

const PREDICT = {
  BY_PEAKS_INIT: 'PREDICT_BY_PEAKS_INIT',
  BY_PEAKS_DONE: 'PREDICT_BY_PEAKS_DONE',
  BY_PEAKS_FAIL: 'PREDICT_BY_PEAKS_FAIL',
};

const RAW = {
  INSERT: 'RAW_INSERT',
  UPDATE_SCAN: 'RAW_UPDATE_SCAN',
  CLEAR_SCAN: 'RAW_CLEAR_SCAN',
  SUBMIT: 'RAW_SUBMIT',
};

export {
  FILE,
  NOTICE,
  PREDICT,
  RAW,
};
